version: "3"

services:
  orion:
    image: fiware/orion
    restart: unless-stopped
    ports:
      - 1026:1026
    depends_on:
      - mongo
    command: -dbhost mongo

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    command: --nojournal
    volumes:
      - ./data:/data/db
